#   Copyright 2022 Entropica Labs
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from os import path, makedirs
from datetime import datetime
import json


def experiment_name(param_type: str,
                    init_type: str,
                    p: int,
                    backend: str):
    """
    Construct the experiment name using the properties of the QAOA
    circuit run on the specified backend

    Parameters
    ----------
    param_type:
            Parameterisation strategy of the QAOAcircuit
    init_type:
            Initialisation type of the QAOA circuit 
    p:
            `p` value, i.e. depth of the QAOA circuit
    backend:
            backend used to run the QAOA computation

    Returns
    -------
    exp_name: 
            The name of experiment as a string constructed via 
            the specified QAOA circuit configuration
    """
    exp_name = f'{param_type}_{init_type}_p={p}_{backend}'
    exp_name = exp_name.lower()
    return exp_name


def entropica_saver(results_dict: dict, username: str,
                    exp_name: str, user_filename: str = None):
    """
    Saves results of QAOA computations on disk for later
    access. The results are saved as JSON objects by 
    default in a fixed folder hierarchy. 

    Parameters
    ----------
    results_dict:
            Python results dictionary that contains all the
            relevant information about the optimization run
    username: str
            Username of the person running the experiments
    exp_name: str
            Experiment generated by the function `experiment_name()`.
            Constructed from circuit configuration information
    user_filename: str
            A custom filename specified by user through `eos_client` 
            interface. Defaults as the time of the experiment.

    Returns
    -------
    None
    """
    date_today = datetime.now().strftime("%Y_%m_%d")
    time_now = datetime.now().strftime("%H-%M")

    base_path = '/home'
    saving_dir = path.join(base_path, username,
                           'qaoa_results', exp_name, date_today)
    # saving_dir = username + '/' + exp_name + '/' + date_today

    if not path.exists(saving_dir):
        makedirs(saving_dir)

    filename = 'result_'+time_now if user_filename == None else user_filename

    # json dump the dict in the location and with the filename defined above
    with open(f'{saving_dir}/{filename}', 'w') as write_file:
        json.dump(results_dict, write_file, indent=3)

    return None
