# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - echo "Creating the notebook folder from .readthedocs.yml"
      - pwd
      - ls -lah
      - mkdir ./docs/source/notebooks
      - cp ./examples/* ./docs/source/notebooks/

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally set the version of Python and requirements required to build your docs
# python:
#    version: 3.8
#    install:
#    - method: pip
#      path: .

python:
  install:
    - requirements: docs/requirements.txt
