coverage:
  precision: 2
  round: down
  range: "40...100"
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        threshold: 0%
