import unittest
import copy
import numpy as np

from openqaoa.algorithms.fqaoa.fqaoa_utils import (
    get_analytical_fermi_orbitals,
    get_fermi_orbitals,
    get_givens_rotation_angle,
    get_statevector,
    generate_random_portfolio_data,
)

"""
Unittest based testing of current implementation of the FQAOA Algorithm
"""

class TestFQAOAUtils(unittest.TestCase):

    def setUp(self):
        self.valid_params = [
            {"n_qubits": 5, "n_fermions": 3, "lattice": "cyclic", "hopping": 1.0}, # cyclic lattice with hopping > 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 3, "lattice": "cyclic", "hopping": -1.0}, # cyclic lattice with hopping < 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": 1.0}, # cyclic lattice with hopping > 0 and even n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": -1.0}, # cyclic lattice with hopping < 0 and even n_femrimons
            {"n_qubits": 5, "n_fermions": 3, "lattice": "chain", "hopping": 1.0}, # chain lattice with hopping > 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 3, "lattice": "chain", "hopping": -1.0}, # chain lattice with hopping < 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "chain", "hopping": 1.0}, # chain lattice with hopping > 0 and even n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "chain", "hopping": -1.0}, # chain lattice with hopping < 0 and even n_femrimons
        ]

        self.invalid_params = [
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": 0.0}, # hopping: 0.0
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": 0.0}, # hopping: 0.0
            {"n_qubits": 3, "n_fermions": 5, "lattice": "cyclic", "hopping": 1.0}, # n_fermions > n_qubits
            {"n_qubits": 3, "n_fermions": 5, "lattice": "chain", "hopping": 1.0}, # n_fermions > n_qubits
            {"n_qubits": 5, "n_fermions": 2, "lattice": "star", "hopping": 1.0}, # unsupported lattice
            {"n_qubits": 5, "n_fermions": 2, "lattice": "full", "hopping": 1.0}, # unsupported lattice
            ]

    def test_fermi_orbitals_equivalence_to_statevector(self):
        """
        Test that get_analytical_fermi_oribalts and get_fermi_orbitals are equivalent by outputting statevector.

        The test consists of generating analytical and numerical free fermi orbitals
        and checking that the respective state vectors are numerically consistent.
        """

        for n_qubits, n_fermions, lattice, hopping in [
                (5, 3, "cyclic", 1.0),
                (5, 2, "cyclic", 1.0)
        ]:
            try:
                orbitals1 = get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            except ValueError as e:
                self.fail(f"Unexpected exception raised: {e}")

            try:
                orbitals2 = get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            except ValueError as e:
                self.fail(f"Unexpected exception raised: {e}")

            statevector = []
            for orbitals in [orbitals1, orbitals2]:
                statevector.append(get_statevector(orbitals))
            # Check statevector[0] = e^(i*theta) * statevector[1].
            self.assertTrue(self.is_close_statevector(statevector), "Statevectors are not equivalent up to a global phase.")

    def test_gicvens_rotation_angle_length(self):
        """
        Test with various valid inputs for get_givens_rotation_angle.

        This test consists of checking that the fermi orbit is diagonalised,
        and the length of the givens rotation angle generated by this diagonalisation.
        """

        for params in self.valid_params:
            n_qubits = params["n_qubits"]
            n_fermions = params["n_fermions"]
            lattice = params["lattice"]
            hopping = params["hopping"]

            if lattice == "cyclic" and hopping > 0.0: orbitals = get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            else: orbitals = get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

            try:
                gtheta = get_givens_rotation_angle(orbitals)
            except ValueError as e:
                self.fail(f"Unexpected exception raised: {e}")

            # Check the diagonal matrix
            self.assertTrue(self.is_left_aligned_diagonal_matrix(orbitals), "orbitals are not diagonalized")

            # Check the length of the returned angles
            expected_length = n_fermions * (n_qubits - n_fermions)
            self.assertEqual(len(gtheta), expected_length, "Incorrect number of Givens rotation angles")

    def test_givens_rotation_to_statevector(self):
        """
        Test get_givens_rotation_angle by outputting statevector.

        The test consists of generating a givens rotation angle by diagonalising the Fermi orbitals
        and confirming that the original Fermi orbit is recovered by applying a givens inverse rotation to the diagonalised Fermi orbit.
        """

        for params in self.valid_params:
            n_qubits = params["n_qubits"]
            n_fermions = params["n_fermions"]
            lattice = params["lattice"]
            hopping = params["hopping"]

            if lattice == "cyclic" and hopping > 0.0: orbitals0 = get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            else: orbitals0 = get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

            orbitals1 = copy.deepcopy(orbitals0)
            gtheta = get_givens_rotation_angle(orbitals1)

            # Set an localized n_fermions state.
            matrix = np.zeros((n_fermions, n_qubits), dtype=float)
            for i in range(min(n_fermions, n_qubits)):
                matrix[i, i] = 1

            # perform givens rotations
            it = (n_qubits-n_fermions)*n_fermions
            for irow in range(n_fermions-1, -1, -1):
                for icol in range(irow+1, n_qubits-n_fermions+irow+1):
                    it = it-1
                    angle = gtheta[it]
                    for ik in range(n_fermions):
                        temp = matrix[ik][icol - 1]
                        matrix[ik][icol - 1] = temp * np.cos(-angle) - matrix[ik][icol] * np.sin(-angle)
                        matrix[ik][icol] = temp * np.sin(-angle) + matrix[ik][icol] * np.cos(-angle)
            statevector = []
            for i, orbitals in enumerate([orbitals0, matrix]):

                try:
                    statevector.append(get_statevector(orbitals))
                except ValueError as e:
                    self.fail(f"Unexpected exception raised: {e}")

            # Check statevector[0] = e^(i*theta) * statevector[1].
            self.assertTrue(self.is_close_statevector(statevector), "statevectors are incorrect")

    # exception handling
    def test_fermi_analytical_orbital_invalid_input(self):
        """Test with various invalid inputs for get_fermi_analytical_orbitals."""

        for n_qubits, n_fermions, lattice, hopping in [
                (3, 5, "cyclic", 1.0), # n_fermions > n_qubits
                (5, 3, "cyclic", -1.0), # hopping < 0.0
                (5, 3, "cyclic", 0.0), # hopping = 0.0
        ]:
            with self.assertRaises(ValueError):
                get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

    def test_fermi_orbital_invalid_input(self):
        """Test with various invalid inputs for get_fermi_orbitals."""

        for params in self.invalid_params:
            n_qubits = params["n_qubits"]
            n_fermions = params["n_fermions"]
            lattice = params["lattice"]
            hopping = params["hopping"]

            with self.assertRaises(ValueError):
                get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

    def test_generate_portfolio_data_shapes(self):
        """Test that the function returns outputs with correct shapes."""
        num_assets, num_days = 10, 15
        # Generate data with the seed
        seed = 1
        mu, sigma, hist_exp = generate_random_portfolio_data(num_assets, num_days, seed)

        # Check the shape
        self.assertEqual(len(mu), num_assets)
        self.assertEqual(len(sigma), num_assets)
        self.assertEqual(len(sigma[0]), num_assets)
        self.assertEqual(hist_exp.shape, (num_assets, num_days))

    def test_generate_portfolio_data_without_seed(self):
        """Test that setting a seed produces the same output."""
        num_assets, num_days = 10, 15
        # Generate data without the seed
        mu1, sigma1, hist_exp1 = generate_random_portfolio_data(num_assets, num_days)
        mu2, sigma2, hist_exp2 = generate_random_portfolio_data(num_assets, num_days)

        # Check that the two runs produce different results
        self.assertNotEqual(mu1, mu2)
        self.assertNotEqual(sigma1, sigma2)
        self.assertFalse(np.array_equal(hist_exp1, hist_exp2))

    @staticmethod
    def is_close_statevector(statevector) -> bool:
        """
        Checks if statevector[0] can be expressed as e^(i*theta) * statevector[1].
        """

        # Threshold for considering a value to be zero
        tolerance = 1e-10

        # Check if statevector[0] is approximately zero where statevector[1] is approximately zero
        zero_mask_1 = np.isclose(statevector[1], 0, atol=tolerance)
        zero_mask_0 = np.isclose(statevector[0], 0, atol=tolerance)

        if np.all(zero_mask_1 == zero_mask_0):
            # Create a mask to avoid division by zero
            non_zero_mask = ~np.isclose(statevector[1], 0, atol=tolerance)

            # Compute the ratio with the mask applied
            ratio = statevector[0][non_zero_mask] / statevector[1][non_zero_mask]

            # Verify if all ratios have the same phase angle
            theta_calculated = np.angle(ratio)
            theta_adjusted = (theta_calculated + np.pi) % (2 * np.pi) - np.pi

            # Check if the phase difference is consistent
            consistent_phase = np.allclose(theta_adjusted, theta_adjusted[0])

            if consistent_phase:
                theta = theta_adjusted[0]
                print(f"statevector[0] can be expressed as e^(i*theta) * statevector[1] with theta={theta}.")
                return True
            print("statevector[0] cannot be expressed as e^(i*theta) * statevector[1].")
            print('theta_adjusted', theta_adjusted)
            return False
        print("It cannot be confirmed that statevector[0] is approximately zero when statevector[1] is approximately zero.")
        for i in range(len(statevector[0])):
            print(statevector[0][i], statevector[1][i])
        return False

    @staticmethod
    def is_left_aligned_diagonal_matrix(matrix: np.ndarray) -> bool:
        """
        Checks if the matrix has the most left-aligned diagonal elements as either 1 or -1,
        and all other elements as 0.
        """

        np.set_printoptions(precision=3, suppress=True, linewidth=100)
        print('fermi orbitals diagonalized by givens rotations')

        rows, cols = matrix.shape
        for i in range(rows):
            for j in range(cols):
                if i == j:  # For diagonal elements
                    if not np.isclose(abs(matrix[i, j]), 1):
                        return False
                else:  # For non-diagonal elements
                    if not np.isclose(matrix[i, j], 0):
                        return False
        return True

if __name__ == '__main__':
    unittest.main()
