import unittest
import copy
import numpy as np

from openqaoa.algorithms.fqaoa.fqaoa_utils import (
    get_analytical_fermi_orbitals,
    get_fermi_orbitals,
    get_givens_rotation_angle,
    get_statevector,
)

"""
Unittest based testing of current implementation of the FQAOA Algorithm
"""

class TestFQAOAUtils(unittest.TestCase):

    def setUp(self):
        self.valid_params = [
            {"n_qubits": 5, "n_fermions": 3, "lattice": "cyclic", "hopping": 1.0}, # cyclic lattice with hopping > 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 3, "lattice": "cyclic", "hopping": -1.0}, # cyclic lattice with hopping < 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": 1.0}, # cyclic lattice with hopping > 0 and even n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": -1.0}, # cyclic lattice with hopping < 0 and even n_femrimons
            {"n_qubits": 5, "n_fermions": 3, "lattice": "chain", "hopping": 1.0}, # chain lattice with hopping > 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 3, "lattice": "chain", "hopping": -1.0}, # chain lattice with hopping < 0 and odd n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "chain", "hopping": 1.0}, # chain lattice with hopping > 0 and even n_femrimons
            {"n_qubits": 5, "n_fermions": 2, "lattice": "chain", "hopping": -1.0}, # chain lattice with hopping < 0 and even n_femrimons
        ]

        self.invalid_params = [
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": 0.0}, # hopping: 0.0
            {"n_qubits": 5, "n_fermions": 2, "lattice": "cyclic", "hopping": 0.0}, # hopping: 0.0
            {"n_qubits": 3, "n_fermions": 5, "lattice": "cyclic", "hopping": 1.0}, # n_fermions > n_qubits
            {"n_qubits": 3, "n_fermions": 5, "lattice": "chain", "hopping": 1.0}, # n_fermions > n_qubits
            {"n_qubits": 5, "n_fermions": 2, "lattice": "star", "hopping": 1.0}, # unsupported lattice
            {"n_qubits": 5, "n_fermions": 2, "lattice": "full", "hopping": 1.0}, # unsupported lattice
            ]

    def test_fermi_orbitals_equivalence_to_statevector(self):
        """
        Test that get_analytical_fermi_orbitals and get_fermi_orbitals are equivalent by outputting statevector.

        The test consists of generating analytical and numerical free fermi orbitals
        and checking that the respective state vectors are numerically consistent.
        """

        for n_qubits, n_fermions, lattice, hopping in [
                (5, 3, "cyclic", 1.0),
                (5, 2, "cyclic", 1.0)
        ]:
            analytical_fermi_orbitals = get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            fermi_orbitals = get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            statevector = [get_statevector(analytical_fermi_orbitals), get_statevector(fermi_orbitals)]
            self.assertTrue(is_close_statevector(statevector[0], statevector[1]),
                            "statevector[0] cannot be expressed as e^(i*theta) * statevector[1].")

    def test_givens_rotation_angle_length(self):
        """
        Test with various valid inputs for get_givens_rotation_angle.

        This test consists of checking that the fermi orbit is diagonalised,
        and the length of the givens rotation angle generated by this diagonalisation.
        """

        for params in self.valid_params:
            n_qubits = params["n_qubits"]
            n_fermions = params["n_fermions"]
            lattice = params["lattice"]
            hopping = params["hopping"]

            if lattice == "cyclic" and hopping > 0.0:
                orbitals = get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            else:
                orbitals = get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

            gtheta = get_givens_rotation_angle(orbitals)

            # Check the diagonal matrix
            self.assertTrue(self.is_left_aligned_diagonal_matrix(orbitals), "orbitals are not diagonalized")

            # Check the length of the returned angles
            expected_length = n_fermions * (n_qubits - n_fermions)
            self.assertEqual(len(gtheta), expected_length, "Incorrect number of Givens rotation angles")

    def test_givens_rotation_to_statevector(self):
        """
        Test get_givens_rotation_angle by outputting statevector.

        The test consists of generating a givens rotation angle by diagonalising the Fermi orbitals
        and confirming that the original Fermi orbit is recovered by applying a givens inverse rotation to the diagonalised Fermi orbit.
        """

        for params in self.valid_params:
            n_qubits = params["n_qubits"]
            n_fermions = params["n_fermions"]
            lattice = params["lattice"]
            hopping = params["hopping"]

            if lattice == "cyclic" and hopping > 0.0:
                orbitals0 = get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)
            else:
                orbitals0 = get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

            orbitals1 = copy.deepcopy(orbitals0)
            gtheta = get_givens_rotation_angle(orbitals1)

            # Set an localized n_fermions state.
            matrix = np.zeros((n_fermions, n_qubits), dtype=float)
            for i in range(min(n_fermions, n_qubits)):
                matrix[i, i] = 1

            # perform givens rotations
            it = (n_qubits-n_fermions)*n_fermions
            for irow in range(n_fermions-1, -1, -1):
                for icol in range(irow+1, n_qubits-n_fermions+irow+1):
                    it = it-1
                    angle = gtheta[it]
                    for ik in range(n_fermions):
                        temp = matrix[ik][icol - 1]
                        matrix[ik][icol - 1] = temp * np.cos(-angle) - matrix[ik][icol] * np.sin(-angle)
                        matrix[ik][icol] = temp * np.sin(-angle) + matrix[ik][icol] * np.cos(-angle)
            statevector = [get_statevector(orbitals0), get_statevector(matrix)]
            self.assertTrue(is_close_statevector(statevector[0], statevector[1]),
                            "statevector[0] cannot be expressed as e^(i*theta) * statevector[1].")

    # exception handling
    def test_fermi_analytical_orbital_invalid_input(self):
        """Test with various invalid inputs for get_fermi_analytical_orbitals."""

        for n_qubits, n_fermions, lattice, hopping in [
                (3, 5, "cyclic", 1.0), # n_fermions > n_qubits
                (5, 3, "cyclic", -1.0), # hopping < 0.0
                (5, 3, "cyclic", 0.0), # hopping = 0.0
                (5, 3, "cyc", 1.0), # lattice = "cyc"
        ]:
            with self.assertRaises(ValueError):
                get_analytical_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

    def test_fermi_orbital_invalid_input(self):
        """Test with various invalid inputs for get_fermi_orbitals."""

        for params in self.invalid_params:
            n_qubits = params["n_qubits"]
            n_fermions = params["n_fermions"]
            lattice = params["lattice"]
            hopping = params["hopping"]

            with self.assertRaises(ValueError):
                get_fermi_orbitals(n_qubits, n_fermions, lattice, hopping)

    @staticmethod
    def is_left_aligned_diagonal_matrix(matrix: np.ndarray) -> bool:
        """
        Checks if the matrix has the most left-aligned diagonal elements as either 1 or -1,
        and all other elements as 0.
        """

        rows, cols = matrix.shape
        for i in range(rows):
            for j in range(cols):
                if i == j:  # For diagonal elements
                    if not np.isclose(abs(matrix[i, j]), 1):
                        return False
                else:  # For non-diagonal elements
                    if not np.isclose(matrix[i, j], 0):
                        return False
        return True

def is_close_statevector(statevector1, statevector2) -> bool:
    """
    Checks if statevector1 can be expressed as e^(i*theta) * statevector2.
    """

    # Threshold for considering a value to be zero
    tolerance = 1e-10

    # Check if statevector1 is approximately zero where statevector2 is approximately zero
    zero_mask_0 = np.isclose(statevector1, 0, atol=tolerance)
    zero_mask_1 = np.isclose(statevector2, 0, atol=tolerance)

    if np.all(zero_mask_1 == zero_mask_0):
        # Create a mask to avoid division by zero
        non_zero_mask = ~np.isclose(statevector2, 0, atol=tolerance)

        # Compute the ratio with the mask applied
        ratio = statevector1[non_zero_mask] / statevector2[non_zero_mask]

        # Verify if all ratios have the same phase angle
        theta_calculated = np.angle(ratio)
        theta_adjusted = (theta_calculated + np.pi) % (2 * np.pi) - np.pi
        consistent_phase = np.allclose(theta_adjusted, theta_adjusted[0])

        # Verify if all absolute values are same
        absolute_ratio = np.abs(statevector1[non_zero_mask] / statevector2[non_zero_mask])
        consistent_magnitude = np.allclose(absolute_ratio, absolute_ratio[0])

        if consistent_phase and consistent_magnitude:
            return True

        return False
    return False

if __name__ == '__main__':
    unittest.main()
