name: Upload Release Package to PyPITest

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: {}

jobs:
  deploy:
    if: github.repository_owner == 'entropicalabs'
    runs-on: ubuntu-latest
    steps:
    - name: Check out opeqaoa
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip build twine
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: |
        python setup.py sdist
        python -m twine upload --repository testpypi dist/*