name: Nightly Upload to Test PyPI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    if: github.repository_owner == 'entropicalabs'
    runs-on: ubuntu-latest
    steps:
    - name: Check out opeqaoa
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        make install requirements
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*